### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by ghost** [rascully/Stream-Monitoring-Data-Exchange-Specifications#46]
No longer need:
- [ ] DataExchangeStandards/TablesforManuscripts/ folder, the files within, or code to create the files within (I am not sure where the code to create this folder/files is. something to investigate)

Small edits to DES Tables:
- [ ] delete 'noteAndConvention' columns (if not already done after next update) - I'm not sure where this column comes from?
- [ ] Delete 'min' and range 'maxrange' columns - this comes from the Mdict: minrange and maxrange fields
- these items are possibly related to this code? https://github.com/rascully/Stream-Monitoring-Data-Exchange-Specifications/blob/master/R/CreateDataTablesMetadataDict.R

MetricControlledVocabulary:
- [ ] Delete 'entity' - comes from CatDict: 'entity'
- [ ] Delete 'attribute' - comes from CatDict: 'attribute'
- [ ] Delete 'sourcedef' - comes from CatDict: 'sourcedef'
- maybe in this code? https://github.com/rascully/Stream-Monitoring-Data-Exchange-Specifications/blob/master/R/CreateDataTablesMetadataDict.R

- [ ] add datasetID to Event and MeasurementOrFact tables - can we make this change simply by adding the field to the MetadataDictionary and re-running the code?

**Comment by ghost** [comment]
- [ ] delete https://github.com/rascully/Stream-Monitoring-Data-Exchange-Specifications/blob/master/DataIntegrationExample/data/RelationalDataTablesStreamHabitatMetrics.xlsx
- [ ] delete https://github.com/rascully/Stream-Monitoring-Data-Exchange-Specifications/blob/master/DataIntegrationExample/data/Integrated%20Data%20Set.accdb
 do these changes impact code or require minor code changes?

- [ ] replace w/ sql db (@edlabo )
